// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flashflow_sentinel/app/data/models/correction_record.dart';
import 'package:flashflow_sentinel/app/data/models/dataset_message.dart';
import 'package:flashflow_sentinel/app/data/models/processed_message.dart';
import 'package:flashflow_sentinel/app/data/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CorrectionRecordAdapter());
    registerAdapter(DatasetMessageAdapter());
    registerAdapter(ProcessedMessageAdapter());
    registerAdapter(TransactionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CorrectionRecordAdapter());
    registerAdapter(DatasetMessageAdapter());
    registerAdapter(ProcessedMessageAdapter());
    registerAdapter(TransactionAdapter());
  }
}
